repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.2
    hooks:
      - id: gitleaks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: check-json
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest tests
        language: system
        pass_filenames: false
        stages: [pre-push]
