body:
  - type: input
    attributes:
      name: username
      label: "Default Username:"
      defaultValue: null
      description: >
        This username is used when no access token is provided. If you provide an access token, this username is ignored.
  - type: passwordBox
    attributes:
      name: token
      label: "Personal access token:"
      defaultValue: ""
      description: >
        This token is not required, but will help mitigate the rate limit of the GitHub API. It is recommended to use a token with minimal scopes.
  - type: dropdown
    attributes:
      name: default_action
      label: "Default Action:"
      defaultValue: "Open in browser"
      options:
        - "Open in Browser"
        - "Open in Desktop Application"
