[tox]
package_name = "src/github_quick_launcher"
envlist = lint, type, py39, py312

[testenv]
deps =
    pytest
    pytest-asyncio
    pytest-httpx
commands =
    pytest {posargs:tests}

[testenv:lint]
description = Run all linting checks
skip_install = false
deps = flake8
commands = flake8 {[tox]package_name} tests

[testenv:type]
description = Run all type checks
skip_install = false
deps = mypy
commands = mypy {[tox]package_name}

[testenv:readme]
description = Render README.md from README.md.j2
skip_install = true
allowlist_externals = readwright
commands = readwright render
