name: "Release-Builder"
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  PYTHON_VER: 3.11
jobs:
  test:
    uses: ./.github/workflows/test-plugin.yml
  deps:
    name: "Build"
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ env.PYTHON_VER }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VER }}
      - name: Bump manifest version from tag
        run: |
          tag="$GITHUB_REF_NAME"
          content=$(jq --arg tag $tag '.Version = $tag' ./src/plugin.json)
          echo $content > ./src/plugin.json
      - name: Build
        run: make build
      - name: Dist
        run: make dist
      - name: Package
        run: make package
      - name: Get zip name
        id: zipname
        run: echo ::set-output name=zipname::$(make zipname)
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: ${{ contains(github.ref_name, '-')}}
          files: "./${{steps.zipname.outputs.zipname}}"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
