name: "Release-Builder"
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
    paths-ignore: 
      - .github/workflows/*
      - README.md
env:
  PYTHON_VER: 3.11
jobs:
  deps:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ env.PYTHON_VER }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VER }}
      - name: Build
        run: make build
      - name: Dist
        run: make dist
      - name: Package
        run: make package
      - name: Get version
        id: version
        run: echo ::set-output name=version::$(jq -r .Version ./src/plugin.json)
      - name: Get zip name
        id: zipname
        run: echo ::set-output name=zipname::$(make zipname)
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          files: "./${{steps.zipname.outputs.zipname}}"
          tag_name: "v${{steps.version.outputs.version}}"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
